export enum NoteActionTypes {
    SET_NOTE_LIST = 'SET_NOTE_LIST',
    SET_NOTE_FILTERS_LIST = 'SET_NOTE_FILTERS_LIST',
    NOTE_DETAIL = 'NOTE_DETAIL',
    ADD_NOTE = 'ADD_NOTE',
    UPDATE_NOTE = 'UPDATE_NOTE',
    DELETE_NOTE = 'DELETE_NOTE',
    SHOW_MODAL_NOTE = 'SHOW_MODAL_NOTE',
    SEARCH_NOTE = 'SEARCH_NOTE',
}
